# Target database file saved to local home profile directory
spring.datasource.url=jdbc:h2:~/jwhisper_db;CIPHER=AES;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver

# Database credentials
spring.datasource.username=${DB_USER_USERNAME}
spring.datasource.password=${DB_FILE_PASSWORD} ${DB_USER_PASSWORD}

# Ensure Spring runs our schema.sql initialization layout template
spring.sql.init.mode=always
