# Target database file saved to local home profile directory
spring.datasource.url=jdbc:h2:./db/jwhisper_db;DB_CLOSE_DELAY=-1;CIPHER=AES;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver

# Database credentials
spring.datasource.username=${DB_USER_USERNAME:sa}
spring.datasource.password=${DB_FILE_PASSWORD:qwerty} ${DB_USER_PASSWORD:123456}

# Ensure Spring runs our schema.sql initialization layout template
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:sql/userdb/schema.sql
